server:
  port: 80

debug: true

# 关系数据库
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: is_deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhihu?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  # 缓存
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 0
    timeout: 0

  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300

# 对象存储
minio:
  endpoint: http://localhost:9000 #Minio服务所在地址
  bucketName: default #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥

# 认证服务
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: zhihu
  resource: zhihu-oidc
  principal-attribute: preferred_username
  bearer-only: false
  use-resource-role-mappings: true
  cors: true
  public-client: true
  security-constraints:
    - authRoles:
        - normal_user
      securityCollections:
        - name: jack
          patterns:
#            - /questions/*
#            - /answer/*
#            - /vote/*
